services:
  - type: web
    name: laravel12-react
    plan: starter
    runtime: docker
    dockerfilePath: ./Dockerfile
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: svc-3482219c-a389-4079-b18b-d50662524e8a-shared-dml.aws-virginia-6.svc.singlestore.com
      - key: DB_PORT
        value: 3333
      - key: DB_DATABASE
        value: db_arnie_7c14c
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
